
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class AntecedenteHereditario
{

    public int IdConsulta { get; set; }

    public byte DM { get; set; }

    public byte HTA { get; set; }

    public byte Asma { get; set; }

    public byte Cardiopatía { get; set; }

    public byte EnfermedadPulmonar { get; set; }

    public byte Hepatopapia { get; set; }

    public byte Neuropatia { get; set; }

    public byte Cancer { get; set; }

    public byte AfeccionTiroide { get; set; }

    public byte AVC { get; set; }

    public string otro { get; set; }



    public virtual Consulta Consulta { private get; set; }

    private Familiar Familiar { get; set; }

    private Familiar Familiar1 { get; set; }

    private Familiar Familiar2 { get; set; }

    private Familiar Familiar3 { get; set; }

    private Familiar Familiar4 { get; set; }

    private Familiar Familiar5 { get; set; }

    private Familiar Familiar6 { get; set; }

    private Familiar Familiar7 { get; set; }

    private Familiar Familiar8 { get; set; }

    private Familiar Familiar9 { get; set; }

}

}
