
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class AntecedentesGinecoObstrectico
{

    public int idConsulta { get; set; }

    public Nullable<System.DateTime> FUM { get; set; }

    public Nullable<byte> Gestaciones { get; set; }

    public Nullable<byte> Partos { get; set; }

    public Nullable<byte> Abortos { get; set; }

    public Nullable<byte> Cecareas { get; set; }

    public Nullable<System.DateTime> FUPAC { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
