//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AntecedentePersonalesPatologico
    {
        public int IdConsulta { get; set; }
        public Nullable<byte> Parotiditis { get; set; }
        public Nullable<byte> Sarampion { get; set; }
        public Nullable<byte> Rubeola { get; set; }
        public Nullable<byte> Varicela { get; set; }
        public Nullable<byte> Fiebre_Reumatica { get; set; }
        public Nullable<byte> Bronquitis { get; set; }
        public Nullable<byte> Paludismo { get; set; }
        public string Detalle { get; set; }
    
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales { private get; set; }
        public virtual Consulta Consulta { private get; set; }
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales1 { private get; set; }
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales2 { private get; set; }
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales3 { private get; set; }
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales4 { private get; set; }
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales5 { private get; set; }
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales6 { private get; set; }
    }
}
