
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ConsultaCuello
{

    public int IdConsulta { get; set; }

    public bool ConfiguracionDelCuello { get; set; }

    public bool Simetrico { get; set; }

    public byte PresionVenosa { get; set; }

    public bool LesionesPiel { get; set; }

    public bool AdenoPatias { get; set; }

    public string ArteriasCarotidas { get; set; }

    public string GangliosLinfaticos { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
