
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ConsultaNariz
{

    public int IdConsulta { get; set; }

    public bool Rinorrea { get; set; }

    public bool Epitaxis { get; set; }

    public bool Sinusitis { get; set; }

    public bool ResfrioFrecuente { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
