
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ConsultaOjo
{

    public int IdConsulta { get; set; }

    public string PerdidaAgudezaVisual { get; set; }

    public bool Diplopia { get; set; }

    public bool FotoFobia { get; set; }

    public bool Lentes { get; set; }

    public bool Xerolftamia { get; set; }

    public bool Epifora { get; set; }

    public bool Midriasis { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
