//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulta
    {
        public Consulta()
        {
            this.ElectroResultados = new HashSet<ElectroResultado>();
            this.GeneralTipoServicios = new HashSet<GeneralTipoServicio>();
            this.AntecedenteDrogra = new HashSet<AntecedenteDrogra>();
            this.AntecedenteVacuna = new HashSet<AntecedenteVacuna>();
            this.Seguimiento = new HashSet<Seguimiento>();
        }
    
        public int IdConsulta { get; set; }
        public int IdCliente { get; set; }
        public System.DateTime FechaConsulta { get; set; }
        public string Diagnostico { get; set; }
        public int CobroFinalDeConsulta { get; set; }
        public Nullable<int> Descuento { get; set; }
        public string PlanTratamiento { get; set; }
        public string AntecenteQuirurgico { get; set; }
        public string MotivoConsulta { get; set; }
        public bool DiagnosticoEstado { get; set; }
        public string PadecimientoActual { get; set; }
        public byte NumeroTiempo { get; set; }
        public string PrimerIndicio { get; set; }
        public string QSucedeAcontinuacion { get; set; }
    
        public virtual AntecedenteHereditario AntecedenteHereditario { private get; set; }
        public virtual AntecedentePersonalesPatologico AntecedentePersonalesPatologico { private get; set; }
        public virtual AntecedentesGinecoObstrectico AntecedentesGinecoObstrectico { private get; set; }
        public virtual Cliente Cliente { private get; set; }
        public virtual ConsultaAparatoDigestivo ConsultaAparatoDigestivo { private get; set; }
        public virtual ConsultaCraneo ConsultaCraneo { private get; set; }
        public virtual ConsultaCuello ConsultaCuello { private get; set; }
        public virtual ConsultaEstadoEmocional ConsultaEstadoEmocional { private get; set; }
        public virtual ConsultaOido ConsultaOido { private get; set; }
        public virtual ConsultaOjo ConsultaOjo { private get; set; }
        public virtual ConsultaParesCraneale ConsultaParesCraneale { private get; set; }
        public virtual ConsultaReflejo ConsultaReflejo { private get; set; }
        public virtual ConsultaSensibilidad ConsultaSensibilidad { private get; set; }
        public virtual ConsultaToraxPulmone ConsultaToraxPulmone { private get; set; }
        public virtual CoordinacionyMarcha CoordinacionyMarcha { private get; set; }
        public virtual ICollection<ElectroResultado> ElectroResultados { private get; set; }
        public virtual ConsultaEstadoVivienda ConsultaEstadoVivienda { private get; set; }
        public virtual ConsultaExploracionFisica ConsultaExploracionFisica { private get; set; }
        public virtual ICollection<GeneralTipoServicio> GeneralTipoServicios { get; set; }
        public virtual ConsultaNariz ConsultaNariz { private get; set; }
        public virtual AntecedenteAlcohol AntecedenteAlcohol { get; set; }
        public virtual ICollection<AntecedenteDrogra> AntecedenteDrogra { get; set; }
        public virtual AntecedenteTabaco AntecedenteTabaco { get; set; }
        public virtual ICollection<AntecedenteVacuna> AntecedenteVacuna { get; set; }
        public virtual GlasgowResultado GlasgowResultado { get; set; }
        public virtual EscalaTiempo EscalaTiempo { get; set; }
        public virtual ConsultaAbdomen ConsultaAbdomen { get; set; }
        public virtual ConsultaBoca ConsultaBoca { get; set; }
        public virtual ICollection<Seguimiento> Seguimiento { get; set; }
    }
}
