//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaOido
    {
        public int IdConsulta { get; set; }
        public bool Acusia { get; set; }
        public bool Hipocusia { get; set; }
        public bool Hipercusia { get; set; }
        public bool Otalgia { get; set; }
        public bool Otorrea { get; set; }
        public bool Tinitus { get; set; }
    
        public virtual Consulta Consulta { private get; set; }
    }
}
