
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ConsultaSensibilidad
{

    public int IdConsulta { get; set; }

    public bool S_Superficial { get; set; }

    public bool S_Profunda { get; set; }

    public bool S_Discriminatoria { get; set; }

    public bool S_Discriminacion_Dos_Puntos { get; set; }

    public string Detalles { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
