//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaEstadoVivienda
    {
        public int IdConsulta { get; set; }
        public bool IsPropia { get; set; }
        public byte Piso { get; set; }
        public bool Cielorraso { get; set; }
        public byte Paredes_Material { get; set; }
        public string ServiciosBasicos { get; set; }
        public byte SanitariosCantidad { get; set; }
        public bool AguaPotable { get; set; }
        public bool TieneMascota { get; set; }
        public string DetalleExtra { get; set; }
        public bool Ventilacion { get; set; }
    
        public virtual Consulta Consulta { private get; set; }
        public virtual ConsultaEstadoViviendaMateriale ConsultaEstadoViviendaMateriale { private get; set; }
        public virtual ConsultaEstadoViviendaMateriale ConsultaEstadoViviendaMateriale1 { private get; set; }
    }
}
