
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ConsultaEstadoEmocional
{

    public int IdConsulta { get; set; }

    public bool Depresion { get; set; }

    public bool Nervioso { get; set; }

    public bool Tensión { get; set; }

    public bool Irritabilidad { get; set; }

    public bool AlteracionSueño { get; set; }

    public bool Alucinaciones { get; set; }

    public string Otro { get; set; }

    public bool Normal { get; set; }

    public bool Debilidad { get; set; }

    public bool Desmayos { get; set; }

    public bool Distraido { get; set; }

    public bool EdadAvanzada { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
