//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaParesCraneale
    {
        public int IdConsulta { get; set; }
        public bool PC_I_Olfatorio { get; set; }
        public bool PC_II_FondoOjo { get; set; }
        public bool PC_II_AgudezaVisual { get; set; }
        public bool PC_II_VisionColores { get; set; }
        public bool PC_II_ReflejoPupilar { get; set; }
        public bool PC_II_Campimetria { get; set; }
        public bool PC_III_IV_VI_MovimientoOcular { get; set; }
        public bool PC_III_IV_VI_ReflejoFotoMotorDirectoyConsensual { get; set; }
        public bool PC_V_SensibilidadCara { get; set; }
        public bool PC_V_ReflejoCorneano { get; set; }
        public bool PC_V_MovimientoMandibula { get; set; }
        public bool PC_VII_MovibilidadMusculosCara { get; set; }
        public bool PC_VII_Gustos2TerciosAnterioresLengua { get; set; }
        public bool PC_VII_CierreOjosVsResistencia { get; set; }
        public bool PC_VII_SoplaMuentraDientes { get; set; }
        public bool PC_VII_MuecasAmbosLado { get; set; }
        public bool PC_VIII_WebberYRinne { get; set; }
        public bool PC_VIII_Romberg { get; set; }
        public bool PC_IX_FunciasGustativa { get; set; }
        public bool PC_X_ElevacionSimetrica { get; set; }
        public bool PC_X_Lengua { get; set; }
        public bool PC_X_Paladar { get; set; }
        public bool PC_X_ReflejoNauseano { get; set; }
        public bool PC_XI_MovimientoEsternocleidomastoideo { get; set; }
        public bool PC_XI_TonoFuerzaMuscarlarEsterno { get; set; }
        public bool PC_XI_MovimientoTrapecio { get; set; }
        public bool PC_XI_TonoFuerzaMuscarlarTrapecio { get; set; }
        public string OtroDetalle { get; set; }
    
        public virtual Consulta Consulta { private get; set; }
    }
}
