//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaToraxPulmone
    {
        public int IdConsulta { get; set; }
        public byte RespiracionDiafragmaticaAbdominal { get; set; }
        public byte ExpasibilidadToraxica { get; set; }
        public byte AscultacionMurmulloVescular { get; set; }
        public byte RuidosAgregados { get; set; }
        public Nullable<bool> SonoridadPulmunar { get; set; }
    
        private Consulta Consulta { get; set; }
        public virtual Consulta_RespuestasGenerales Consulta_RespuestasGenerales { get; private set; }
        private Consulta_RespuestasGenerales Consulta_RespuestasGenerales1 { get; set; }
        private Consulta_RespuestasGenerales Consulta_RespuestasGenerales2 { get; set; }
        private Consulta_RespuestasGenerales Consulta_RespuestasGenerales3 { get; set; }
    }
}
