//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConsultaEstadoViviendaMateriale
    {
        public ConsultaEstadoViviendaMateriale()
        {
            this.ConsultaEstadoViviendas = new HashSet<ConsultaEstadoVivienda>();
            this.ConsultaEstadoViviendas1 = new HashSet<ConsultaEstadoVivienda>();
        }
    
        public byte IdMaterial { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<ConsultaEstadoVivienda> ConsultaEstadoViviendas { private get; set; }
        public virtual ICollection<ConsultaEstadoVivienda> ConsultaEstadoViviendas1 { private get; set; }
    }
}
