
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ConsultaAparatoDigestivo
{

    public int IdConsulta { get; set; }

    public bool Dolor { get; set; }

    public bool FaltaApetito { get; set; }

    public bool Nauseas { get; set; }

    public byte Vomito { get; set; }

    public bool Diarrea { get; set; }

    public bool Estreñimiento { get; set; }

    public bool Pirosis { get; set; }

    public bool Colicos { get; set; }

    public bool Distencion { get; set; }

    public string Detalles { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
