
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class CoordinacionyMarcha
{

    public int IdConsulta { get; set; }

    public bool Dedo_Nariz { get; set; }

    public bool Talon_Rodilla { get; set; }

    public bool Romberg { get; set; }

    public bool Camina { get; set; }

    public string Observacion { get; set; }



    public virtual Consulta Consulta { private get; set; }

}

}
