
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class ElectroResultado
{

    public int idConsulta { get; set; }

    public int idCliente { get; set; }

    public byte[] ElectroResultado1 { get; set; }



    public virtual Cliente Cliente { private get; set; }

    public virtual Consulta Consulta { private get; set; }

}

}
