//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Examene
    {
        public int idExamenes { get; set; }
        public Nullable<int> idCliente { get; set; }
        public Nullable<int> FechaConsulta { get; set; }
        public Nullable<int> idTipoExamen { get; set; }
        public Nullable<System.DateTime> FechaEntragaResultado { get; set; }
        public Nullable<int> EstadoPagado { get; set; }
        public Nullable<int> EstadoExamen { get; set; }
    
        public virtual Cliente Cliente { private get; set; }
        public virtual TipoExamene TipoExamene { private get; set; }
        public virtual ExamenesResultado ExamenesResultado { private get; set; }
    }
}
