
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class FuenteIngreso
{

    public FuenteIngreso()
    {

        this.Gastos = new HashSet<Gasto>();

        this.Ingresos = new HashSet<Ingreso>();

    }


    public int IdFuenteIngreso { get; set; }

    public string Nombre { get; set; }



    public virtual ICollection<Gasto> Gastos { private get; set; }

    public virtual ICollection<Ingreso> Ingresos { private get; set; }

    public virtual TipoUsuario TipoUsuario { get; set; }

}

}
