
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class Gasto
{

    public int IdGastos { get; set; }

    public int IdTipoUsuario { get; set; }

    public int CantidadGasto { get; set; }

    public string DescripcionBreve { get; set; }

    public System.DateTime FechaDeGasto { get; set; }



    public virtual CategoriasGasto CategoriasGasto { get; set; }

    public virtual FuenteIngreso FuenteIngreso { get; set; }

    public virtual TipoUsuario TipoUsuario { get; set; }

}

}
