//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ingresos
    {
        public int IdIngreso { get; set; }
        public int IdTipoUsuario { get; set; }
        public int CantidadIngreso { get; set; }
        public System.DateTime FechaDeIngreso { get; set; }
        public string DescripcionBreve { get; set; }
    
        public virtual CategoriaIngreso CategoriaIngreso { get; set; }
        public virtual FuenteIngreso FuenteIngreso { get; set; }
        public virtual TipoUsuario TipoUsuario { get; set; }
    }
}
