
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class InventarioMedicina
{

    public InventarioMedicina()
    {

        this.GeneralTipoServicio = new HashSet<GeneralTipoServicio>();

    }


    public int IdArticulo { get; set; }

    public string Nombre { get; set; }

    public int Precio { get; set; }

    public int CantidadAlerta { get; set; }

    public string Presentacion { get; set; }

    public int CantidadActual { get; set; }



    public virtual InventarioEstado InventarioEstado { get; set; }

    public virtual ICollection<GeneralTipoServicio> GeneralTipoServicio { get; set; }

    public virtual InventarioTipoUnidad InventarioTipoUnidad { get; set; }

}

}
