//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoAlergia
    {
        public TipoAlergia()
        {
            this.ClienteAlergias = new HashSet<ClienteAlergia>();
        }
    
        public int idAlergia { get; set; }
        public string Especificacion { get; set; }
        public string Tipo_Alergia { get; set; }
    
        public virtual ICollection<ClienteAlergia> ClienteAlergias { private get; set; }
    }
}
