
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TipoCita
{

    public TipoCita()
    {

        this.Citas = new HashSet<Cita>();

    }


    public int idTipoCita { get; set; }

    public string Nombre { get; set; }



    public virtual ICollection<Cita> Citas { private get; set; }

}

}
