
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class TipoUsuario
{

    public TipoUsuario()
    {

        this.FuenteIngresoes = new HashSet<FuenteIngreso>();

        this.Gastos = new HashSet<Gasto>();

        this.Ingresos = new HashSet<Ingreso>();

        this.Usuarios = new HashSet<Usuario>();

    }


    public int IdTipoUsuario { get; set; }

    public string NombreTipo { get; set; }



    public virtual ICollection<FuenteIngreso> FuenteIngresoes { get; set; }

    public virtual ICollection<Gasto> Gastos { get; set; }

    public virtual ICollection<Ingreso> Ingresos { get; set; }

    public virtual ICollection<Usuario> Usuarios { get; set; }

}

}
