//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoUsuario
    {
        public TipoUsuario()
        {
            this.GastosGenerales = new HashSet<GastosGenerale>();
            this.Usuarios = new HashSet<Usuario>();
        }
    
        public int idTipoUsuairo { get; set; }
        public string NombreTipo { get; set; }
    
        public virtual ICollection<GastosGenerale> GastosGenerales { private get; set; }
        public virtual ICollection<Usuario> Usuarios { private get; set; }
    }
}
