
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VistaExploracionFisica
{

    public int Número_Consulta { get; set; }

    public string Manos { get; set; }

    public string Color { get; set; }

    public decimal Peso { get; set; }

    public Nullable<decimal> Temperatura { get; set; }

    public decimal Talla { get; set; }

    public Nullable<byte> PresionArterialDiastolico { get; set; }

    public Nullable<byte> PresionArterialSistolico { get; set; }

    public Nullable<byte> FrecuenciaCardiaca { get; set; }

    public Nullable<byte> FrecuenciaRespiratoria { get; set; }

    public Nullable<decimal> IndiceMasaCorporal { get; set; }

}

}
