
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VistaIngreso
{

    public int IdTipoUsuario { get; set; }

    public int IdIngreso { get; set; }

    public string Categoría { get; set; }

    public int CantidadIngreso { get; set; }

    public string Fuente_Ingreso { get; set; }

    public string DescripcionBreve { get; set; }

    public System.DateTime FechaDeIngreso { get; set; }

}

}
