
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VistaToraxPulmones
{

    public int Número_Consulta { get; set; }

    public string Ascultacion_Murmullo_Vescular { get; set; }

    public string ExpasibilidadToraxica { get; set; }

    public string Respiración_Diafragmatica_Abdominal { get; set; }

    public string RuidosAgregados { get; set; }

    public Nullable<bool> SonoridadPulmunar { get; set; }

}

}
