
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VistaConsulta
{

    public int Número_Consulta { get; set; }

    public int IdCliente { get; set; }

    public string Nombre { get; set; }

    public byte Edad { get; set; }

    public System.DateTime FechaConsulta { get; set; }

    public string Diagnostico { get; set; }

    public string PlanTratamiento { get; set; }

    public int CobroFinalDeConsulta { get; set; }

    public Nullable<int> Descuento { get; set; }

    public string Bien_Última_vez { get; set; }

    public string PadecimientoActual { get; set; }

    public string PrimerIndicio { get; set; }

    public string QSucedeAcontinuacion { get; set; }

    public bool Diagnostico_Confirmado { get; set; }

}

}
