//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClinicaPro.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class VistaEstadoVivienda
    {
        public int Número_Consulta { get; set; }
        public bool Es_Casa_Propia { get; set; }
        public string Paredes { get; set; }
        public string Piso { get; set; }
        public bool Cielorraso { get; set; }
        public bool AguaPotable { get; set; }
        public byte SanitariosCantidad { get; set; }
        public string ServiciosBasicos { get; set; }
        public bool TieneMascota { get; set; }
        public bool Ventilacion { get; set; }
        public string DetalleExtra { get; set; }
    }
}
