
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VistaAntecedentesPatologicos
{

    public int Número_Consulta { get; set; }

    public string Paludismo { get; set; }

    public string Parotiditis { get; set; }

    public string Rubéola { get; set; }

    public string Sarampión { get; set; }

    public string Varicela { get; set; }

    public string Bronquitis { get; set; }

    public string Fiebre_Reumática { get; set; }

}

}
