
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ClinicaPro.Entities
{

using System;
    using System.Collections.Generic;
    
public partial class VistaAntecedenteHereditario
{

    public int Número_Consulta { get; set; }

    public string Afección_Tiroide { get; set; }

    public string Asma { get; set; }

    public string AVC { get; set; }

    public string Cancer { get; set; }

    public string Cardiopatía { get; set; }

    public string DM { get; set; }

    public string Enfermedad_Pulmonar { get; set; }

    public string Hepatopapia { get; set; }

    public string HTA { get; set; }

    public string Neuropatia { get; set; }

    public string otro { get; set; }

}

}
